name: tasty
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2
  path: ^1.8.0
  http: ^0.13.4
  font_awesome_flutter: 10.4.0
  flutter_credit_card: ^3.0.6
  rounded_background_text: ^0.3.0
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/successful.png
    - assets/img/logo.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
